name: omnify
description: "Omnify hosts a multi-chain suite of defi products and services faciliating seamless transactions through the security of smart contracts."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  card_swiper: ^3.0.1
  restart_app: ^1.2.1
  scroll_loop_auto_scroll: ^0.0.5
  data_table_2: ^2.5.11
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.3.13
  primer_progress_bar: ^0.4.2
  extended_image: ^8.2.1
  decimal: ^3.0.2
  bs58check: ^1.0.2
  url_launcher: ^6.3.0
  walletconnect_flutter_v2: ^2.3.1
  toastification: ^2.0.0
  qr_flutter_wc: ^0.0.3
  rxdart: ^0.28.0
  web_socket_channel: ^2.4.4
  web3dart: ^2.7.3
  http: ^1.2.2
  hex: ^0.2.0
  loading_animation_widget: ^1.2.1
  custom_timer: ^0.2.3
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_wc.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
